Topic 1:  Fetching Financial Data

Fetching financial data from Yfinanace

In [39]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sn
import yfinance as yf
from datetime import date

In [4]:
Reliance = yf.Ticker("RELIANCE.NS")

In [7]:
Reliance.info

{'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 2535.5,
 'open': 2528.9,
 'dayLow': 2512.0,
 'dayHigh': 2533.4,
 'regularMarketPreviousClose': 2535.5,
 'regularMarketOpen': 2528.9,
 'regularMarketDayLow': 2512.0,
 'regularMarketDayHigh': 2533.4,
 'trailingPE': 28.798256,
 'forwardPE': 35.0,
 'volume': 3057360,
 'regularMarketVolume': 3057360,
 'averageVolume': 5281462,
 'averageVolume10days': 4664834,
 'averageDailyVolume10Day': 4664834,
 'bid': 0.0,
 'ask': 0.0,
 'bidSize': 0,
 'askSize': 0,
 'marketCap': 17014772989952,
 'fiftyTwoWeekLow': 2180.0,
 'fiftyTwoWeekHigh': 2755.0,
 'fiftyDayAverage': 2458.07,
 'twoHundredDayAverage': 2453.862,
 'trailingAnnualDividendRate': 0.0,
 'trailingAnnualDividendYield': 0.0,
 'currency': 'INR',
 'exchange': 'NSI',
 'quoteType': 'EQUITY',
 'symbol': 'RELIANCE.NS',
 'underlyingSymbol': 'RELIANCE.NS',
 'shortName': 'RELIANCE INDS',
 'longName': 'Reliance Industries Limited',
 'firstTradeDateEpochUtc': 820467900,
 'timeZoneFullName': 'Asia/Kolkata',
 'timeZoneShortName': 'IST',
 'uuid': '6fb3aba7-25b9-3826-85a7-5fb8a94f4e84',
 'messageBoardId': 'finmb_878373',
 'gmtOffSetMilliseconds': 19800000,
 'currentPrice': 2514.75,
 'targetHighPrice': 2830.0,
 'targetLowPrice': 1350.0,
 'targetMeanPrice': 2272.1,
 'targetMedianPrice': 2280.0,
 'recommendationMean': 2.1,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 29,
 'grossProfits': 1722910000000,
 'financialCurrency': 'INR',
 'trailingPegRatio': None}

get historical market data - OHLC

In [9]:
historical_data_reliance_eod = Reliance.history(period="1mo")

In [10]:
historical_data_reliance_eod

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2023-05-23 00:00:00+05:30,2460.649902,2468.000000,2451.449951,2454.550049,2811473,0.0,0.0
2023-05-24 00:00:00+05:30,2445.899902,2464.000000,2433.449951,2440.250000,3743804,0.0,0.0
2023-05-25 00:00:00+05:30,2433.899902,2449.000000,2416.050049,2439.949951,5301647,0.0,0.0
2023-05-26 00:00:00+05:30,2458.000000,2509.000000,2450.750000,2506.500000,5827017,0.0,0.0
2023-05-29 00:00:00+05:30,2521.000000,2530.000000,2507.199951,2520.600098,4619754,0.0,0.0
2023-05-30 00:00:00+05:30,2520.600098,2537.699951,2514.350098,2519.949951,5234564,0.0,0.0
2023-05-31 00:00:00+05:30,2500.000000,2509.850098,2461.000000,2469.899902,12510304,0.0,0.0
2023-06-01 00:00:00+05:30,2480.149902,2484.899902,2458.000000,2463.250000,6734525,0.0,0.0
2023-06-02 00:00:00+05:30,2471.000000,2482.850098,2451.000000,2455.199951,7291995,0.0,0.0
2023-06-05 00:00:00+05:30,2467.199951,2483.750000,2458.449951,2477.250000,5034355,0.0,0.0
2023-06-06 00:00:00+05:30,2483.449951,2487.699951,2462.000000,2479.350098,3458161,0.0,0.0
2023-06-07 00:00:00+05:30,2487.000000,2500.000000,2472.600098,2498.149902,4759238,0.0,0.0
2023-06-08 00:00:00+05:30,2506.000000,2516.850098,2491.000000,2499.649902,5570815,0.0,0.0
2023-06-09 00:00:00+05:30,2507.000000,2508.550049,2478.000000,2481.949951,2712243,0.0,0.0
2023-06-12 00:00:00+05:30,2475.500000,2489.199951,2465.000000,2484.149902,2949893,0.0,0.0
2023-06-13 00:00:00+05:30,2495.000000,2523.449951,2486.250000,2520.850098,5190958,0.0,0.0
2023-06-14 00:00:00+05:30,2521.000000,2555.000000,2517.000000,2551.850098,6127509,0.0,0.0
2023-06-15 00:00:00+05:30,2551.800049,2562.550049,2535.500000,2552.550049,5451926,0.0,0.0
2023-06-16 00:00:00+05:30,2560.199951,2582.399902,2560.199951,2577.399902,11155180,0.0,0.0
2023-06-19 00:00:00+05:30,2584.000000,2584.000000,2542.649902,2551.800049,3137532,0.0,0.0
2023-06-20 00:00:00+05:30,2547.550049,2564.000000,2535.000000,2557.100098,3194085,0.0,0.0
2023-06-21 00:00:00+05:30,2557.000000,2569.850098,2548.000000,2564.300049,3212779,0.0,0.0
2023-06-22 00:00:00+05:30,2556.000000,2573.300049,2532.000000,2535.500000,3516244,0.0,0.0
2023-06-23 00:00:00+05:30,2528.899902,2533.399902,2512.000000,2514.750000,3057360,0.0,0.0

In [13]:
rel = pd.DataFrame(Reliance.news)

In [19]:
rel.head(10)

,uuid,title,publisher,link,providerPublishTime,type,thumbnail,relatedTickers
0,f3677a4f-be99-3c1f-a034-7be226577736,Horizon Therapeutics plc,GlobeNewswire,https://finance.yahoo.com/news/horizon-therape...,1687531320,STORY,NaN,NaN
1,0f3bbe90-f17f-387b-9f59-9ca65013fae1,Announcement of the Release of Guidelines for ...,PR Newswire,https://finance.yahoo.com/news/announcement-re...,1687531260,STORY,{'resolutions': [{'url': 'https://s.yimg.com/u...,NaN
2,7899f189-fa66-3510-84d4-ccb1fad0187e,EU governments converge on options to use Russ...,Reuters,https://finance.yahoo.com/news/eu-governments-...,1687531232,STORY,NaN,NaN
3,c36daea3-361c-3a1a-b56a-5f375e351c4e,A Popular European Tourist Destination Just Ma...,TheStreet.com,https://finance.yahoo.com/m/c36daea3-361c-3a1a...,1687531200,STORY,{'resolutions': [{'url': 'https://s.yimg.com/u...,NaN
4,0a034a74-74e6-3589-bb61-0fd407cbe8d2,The global strategy video game market is expec...,GlobeNewswire,https://finance.yahoo.com/news/global-strategy...,1687531080,STORY,{'resolutions': [{'url': 'https://s.yimg.com/u...,NaN
5,a1cc0c3c-67ae-34f5-9e62-87fab3b688fc,CANADA STOCKS-TSX hits three-month low as ener...,Reuters,https://finance.yahoo.com/news/canada-stocks-t...,1687531022,STORY,NaN,NaN
6,4e2fc265-1b31-3890-a8cf-b187c7bae6e4,Clean Energy’s Latest Problem Is Creaky Wind T...,The Wall Street Journal,https://finance.yahoo.com/m/4e2fc265-1b31-3890...,1687530960,STORY,{'resolutions': [{'url': 'https://s.yimg.com/u...,"[SMEGF, SMNEY]"
7,6db23549-6165-3fa9-86e5-8e49211e09da,Smirnoff ICE Hits the Road for Summer As Relau...,PR Newswire,https://finance.yahoo.com/news/smirnoff-ice-hi...,1687530960,STORY,{'resolutions': [{'url': 'https://s.yimg.com/u...,"[DEO, DGEAF]"

In [21]:
 rel.drop("uuid", axis =1)

,title,publisher,link,providerPublishTime,type,thumbnail,relatedTickers
0,Horizon Therapeutics plc,GlobeNewswire,https://finance.yahoo.com/news/horizon-therape...,1687531320,STORY,NaN,NaN
1,Announcement of the Release of Guidelines for ...,PR Newswire,https://finance.yahoo.com/news/announcement-re...,1687531260,STORY,{'resolutions': [{'url': 'https://s.yimg.com/u...,NaN
2,EU governments converge on options to use Russ...,Reuters,https://finance.yahoo.com/news/eu-governments-...,1687531232,STORY,NaN,NaN
3,A Popular European Tourist Destination Just Ma...,TheStreet.com,https://finance.yahoo.com/m/c36daea3-361c-3a1a...,1687531200,STORY,{'resolutions': [{'url': 'https://s.yimg.com/u...,NaN
4,The global strategy video game market is expec...,GlobeNewswire,https://finance.yahoo.com/news/global-strategy...,1687531080,STORY,{'resolutions': [{'url': 'https://s.yimg.com/u...,NaN
5,CANADA STOCKS-TSX hits three-month low as ener...,Reuters,https://finance.yahoo.com/news/canada-stocks-t...,1687531022,STORY,NaN,NaN
6,Clean Energy’s Latest Problem Is Creaky Wind T...,The Wall Street Journal,https://finance.yahoo.com/m/4e2fc265-1b31-3890...,1687530960,STORY,{'resolutions': [{'url': 'https://s.yimg.com/u...,"[SMEGF, SMNEY]"
7,Smirnoff ICE Hits the Road for Summer As Relau...,PR Newswire,https://finance.yahoo.com/news/smirnoff-ice-hi...,1687530960,STORY,{'resolutions': [{'url': 'https://s.yimg.com/u...,"[DEO, DGEAF]"

In [40]:
import talib
import ta

ModuleNotFoundError: No module named 'talib'

In [41]:
pip install talib

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement talib (from versions: none)
ERROR: No matching distribution found for talib

In [42]:
pip install ta

Collecting ta
  Downloading ta-0.10.2.tar.gz (25 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: numpy in c:\users\nehag\appdata\local\programs\python\python311\lib\site-packages (from ta) (1.24.3)
Requirement already satisfied: pandas in c:\users\nehag\appdata\local\programs\python\python311\lib\site-packages (from ta) (2.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\nehag\appdata\local\programs\python\python311\lib\site-packages (from pandas->ta) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\nehag\appdata\local\programs\python\python311\lib\site-packages (from pandas->ta) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in c:\users\nehag\appdata\local\programs\python\python311\lib\site-packages (from pandas->ta) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\nehag\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas->ta) (1.16.0)
Building wheels for collected packages: ta
  Building wheel for ta (setup.py): started
  Building wheel for ta (setup.py): finished with status 'done'
  Created wheel for ta: filename=ta-0.10.2-py3-none-any.whl size=29098 sha256=13c67b8d55ca2c39fd680cfd3f63b17688bf7b41076e047dd39c172ecac00bb8
  Stored in directory: c:\users\nehag\appdata\local\pip\cache\wheels\dd\a5\1b\04c9ab22e30c7d2c1810f0441356918ff458b493b4efaf5249
Successfully built ta
Installing collected packages: ta
Successfully installed ta-0.10.2
Note: you may need to restart the kernel to use updated packages.